final List<String> categories = [
    'All',
    'Nike',
    'Adidas',
    'Puma',
    'Reebok',
    'New Balance',
    'Asics',
    'Under Armour',
    'Converse',
    'Vans',
    'Fila',
    'Jordan',
    'Skechers',
    'Saucony',
    'Hoka',
    'Brooks',
    'Mizuno',
    'On Running',
    'Balenciaga',
    'Yeezy',
  ];